package MindMap.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Mindmap_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("\\documentclass{article}");
    tgs.newLine();
    tgs.append("\\begin{document}");
    tgs.newLine();
    tgs.append("\\title{");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.topic$L2MV), PROPS.name$MnvL));
    tgs.append("}");
    tgs.newLine();
    tgs.append("\\author{");
    tgs.append("}");
    tgs.newLine();
    tgs.append("\\maketitle");
    tgs.newLine();
    tgs.append("\\begin{abstract}");
    tgs.newLine();
    tgs.append("\\end{abstract}");
    tgs.newLine();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.topic$L2MV));
    tgs.newLine();

    tgs.append("\\end{document}");
    tgs.newLine();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink topic$L2MV = MetaAdapterFactory.getContainmentLink(0x95a2956fc69940d4L, 0x9dc6e6a61c0eea29L, 0x23cd11bbeae6d30eL, 0x23cd11bbeae6d31cL, "topic");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
